name: 'TechSee AI PR Reviewer'
description: 'AI-powered PR reviewer that respects Cursor AI rules'
author: 'Amit Wagner'

branding:
  icon: 'eye'
  color: 'blue'

inputs:
  pr_number:
    description: 'PR number to review (required for manual workflow_dispatch)'
    required: false
    
  gh_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  
  openai_api_key:
    description: 'OpenAI API key for AI reviews'
    required: false
    
  anthropic_api_key:
    description: 'Anthropic API key for AI reviews'
    required: false
    
  azure_openai_api_key:
    description: 'Azure OpenAI API key for AI reviews'
    required: false
    
  azure_openai_endpoint:
    description: 'Azure OpenAI endpoint URL (e.g., https://your-resource.openai.azure.com/)'
    required: false
    
  azure_openai_api_version:
    description: 'Azure OpenAI API version (e.g., 2024-10-21 for stable, 2025-04-01-preview for latest features)'
    required: false
    default: '2024-10-21'
    
  ai_provider:
    description: 'AI provider to use (openai, anthropic, azure, or auto)'
    required: false
    default: 'auto'
    
  model:
    description: 'AI model to use. OpenAI: gpt-4o, gpt-4, gpt-4o-mini, gpt-3.5-turbo, etc. Anthropic: claude-3-5-sonnet-20241022, claude-3-opus-20240229, claude-3-haiku-20240307, etc. Use "auto" for intelligent selection based on review_level.'
    required: false
    default: 'auto'
    
  review_level:
    description: 'Review intensity level (light, standard, thorough)'
    required: false
    default: 'standard'
    
  rules_path:
    description: 'Custom path to cursor rules (if not in standard locations)'
    required: false
    
  include_patterns:
    description: 'File patterns to include in review (comma-separated)'
    required: false
    default: '**/*.ts,**/*.tsx,**/*.js,**/*.jsx,**/*.py,**/*.go,**/*.rs,**/*.java,**/*.cs'
    
  exclude_patterns:
    description: 'File patterns to exclude from review (comma-separated)'
    required: false
    default: 'node_modules/**,dist/**,build/**,coverage/**,*.min.js,*.bundle.js'
    
  max_files:
    description: 'Maximum number of files to review in a single PR'
    required: false
    default: '50'
    
  comment_style:
    description: 'Style of review comments (inline, summary, both)'
    required: false
    default: 'both'
    
  inline_severity:
    description: 'Minimum severity for inline comments (error, warning, info, all)'
    required: false
    default: 'error'
    
  summary_format:
    description: 'Format of summary comment (brief, detailed, minimal)'
    required: false
    default: 'detailed'
    
  log_level:
    description: 'Minimum severity level for posting comments (error, warning, info, all)'
    required: false
    default: 'error'

  enable_suggestions:
    description: 'Enable suggestion code blocks in inline comments'
    required: false
    default: 'true'

  skip_if_no_rules:
    description: 'Skip review if no cursor rules are found'
    required: false
    default: 'false'
    
  update_existing_comments:
    description: 'Update existing bot comments instead of creating new ones'
    required: false
    default: 'true'
    
  enable_auto_fix:
    description: 'Enable automatic fixing of eligible issues'
    required: false
    default: 'false'
    
  auto_fix_severity:
    description: 'Minimum severity for auto-fix (error, warning, info, all)'
    required: false
    default: 'error'
    
  request_delay:
    description: 'Delay in milliseconds between AI provider requests to avoid rate limits (default: 2000)'
    required: false
    default: '2000'
    
  batch_size:
    description: 'Number of files to process in each batch (default: 50)'
    required: false
    default: '50'
    
  github_rate_limit:
    description: 'Delay in milliseconds between GitHub API calls to avoid rate limits (default: 1000)'
    required: false
    default: '1000'

outputs:
  review_summary:
    description: 'Summary of the review results'
  files_reviewed:
    description: 'Number of files reviewed'
  issues_found:
    description: 'Number of potential issues found'
  rules_applied:
    description: 'Number of cursor rules applied'

runs:
  using: 'node20'
  main: 'dist/main.js'
