name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Extract version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh release create ${{ github.ref }} \
          --title "Release ${{ steps.version.outputs.VERSION }}" \
          --notes "## 🤖 Cursor AI PR Reviewer v${{ steps.version.outputs.VERSION }}
        
        ### Usage
        \`\`\`yaml
        - uses: amit.wagner/pr-reviewer@v${{ steps.version.outputs.VERSION }}
          with:
            openai_api_key: \${{ secrets.OPENAI_API_KEY }}
            review_level: 'standard'
        \`\`\`
        
        ### What's Changed
        - See commit history for detailed changes
        
        **Full Changelog**: https://github.com/amit.wagner/pr-reviewer/commits/v${{ steps.version.outputs.VERSION }}"

  update-major-tag:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Update major version tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        # Delete existing major tag
        git push origin :refs/tags/v$MAJOR_VERSION || true
        
        # Create new major tag
        git tag -fa v$MAJOR_VERSION -m "Update v$MAJOR_VERSION to v$VERSION"
        git push origin v$MAJOR_VERSION
